config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get '/:id/project_specific_fields/new', to: 'project_specific_fields#new'
post '/:id/project_specific_fields/create', to: 'project_specific_fields#create'
resources 'project_specific_fields', :only => [ :show, :edit, :update, :destroy]
  

app/models/p_spec_issue_custom_field.rb
#The hideously abbreviated name for this class is to solve the redmine 30 character limit on custom field type names
class PSpecIssueCustomField < CustomField
  unloadable
  
  include Redmine::I18n
  
  attr_accessor 'project'
  attr_accessor 'share_with_subprojects'
  
  validates_presence_of 'project'
  after_initialize 'initialize_project'
  after_initialize 'initialize_share_with_subproject'
  after_create 'create_projects'
  after_save 'update_share_with_subprojects'
  has_one :project_specific_custom_fields_project, :dependent => :destroy, :foreign_key => 'custom_field_id'
  has_and_belongs_to_many :trackers, :join_table => "#{table_name_prefix}custom_fields_trackers#{table_name_suffix}", :foreign_key => "custom_field_id"

  validate do
    #if we get an error that the name has already been taken, and it is the only name error,
    # delete it if it is unique for the project
    errors.each do |attribute, error|
      if attribute == :name and errors.get(attribute).size == 1 and error == I18n.t(:taken, scope: [:activerecord, :errors, :messages]) and name_unique_for_project?()
        errors.delete(attribute)
      end
    end
  end
  
  def type_name
    :label_project_specific_issue_custom_field_plural
  end
  
  def visible_by?(project, user=User.current)
    super || (roles & user.roles_for_project(project)).present?
  end
  
  def initialize_project
    cfp = custom_field_project
    self.project = cfp.project unless cfp.nil?
  end
  
  def initialize_share_with_subproject
    cfp = custom_field_project
    self.share_with_subprojects = cfp.nil? ? true : cfp.share_with_subprojects
  end
  
  def create_projects
    self.project.project_specific_issue_custom_fields << self
    self.project.save
  end
  
  def update_share_with_subprojects
    cfp = custom_field_project
    cfp.share_with_subprojects = self.share_with_subprojects
    cfp.save
  end
  
  def self.customized_class
    Issue
  end
  
  def share_with_subprojects?
    self.share_with_subprojects
  end
  
  private
  def name_unique_for_project?()
    for f in IssueCustomField.all + self.project.project_specific_issue_custom_fields
      if (self.name == f.name) and (self.field_format == f.field_format) and (f != self)
        return false
      end
    end
    true
  end
  
  def custom_field_project
    ProjectSpecificCustomFieldsProject.where(:custom_field_id => self.id).first unless self.id.nil?
  end
  
end

app/models/project_specific_custom_fields_project.rb
class ProjectSpecificCustomFieldsProject < ActiveRecord::Base
  unloadable
  
  include Redmine::SafeAttributes
  
  belongs_to :project
  belongs_to :custom_field
  
  safe_attributes :share_with_subprojects
end

app/models/project_specific_issue_field.rb
class ProjectSpecificIssueField < CustomField
  unloadable
  
  attr_accessor 'project'
  
  validates_presence_of 'project'
  after_initialize 'initialize_project'
  after_create 'create_projects'
  has_one :project_specific_custom_fields_project, :dependent => :destroy, :foreign_key => 'custom_field_id'

  def type_name
    :label_project_specific_issue_plural
  end
  
  validate do
    #if we get an error that the name has already been taken, and it is the only name error,
    # delete it if it is unique for the project
    errors.each do |attribute, error|
      if attribute == :name and errors.get(attribute).size == 1 and error == "has already been taken" and name_unique_for_project?()
        errors.delete(attribute)
      end
    end
  end
  
  def initialize_project
    cfp = ProjectSpecificCustomFieldsProject.where(:custom_field_id => self.id).first unless self.id.nil?
    self.project = cfp.project unless cfp.nil?
  end
  
  def create_projects
    self.project.project_specific_issue_custom_fields << self
    self.project.save
  end
  
  private
  def name_unique_for_project?()
    for f in IssueCustomField.all + self.project.project_specific_issue_custom_fields
      if (self.name == f.name) and (self.field_format == f.field_format)
        return false
      end
    end
    true
  end
  
end

app/controllers/project_specific_fields_controller.rb
class ProjectSpecificFieldsController < ApplicationController
  unloadable

  before_filter :find_field, :except => [:new, :create]
  before_filter :find_project, :only => [:new, :create]
  before_filter :authorize
  before_filter :build_field_from_params, :only => [:new, :create]
  
  helper 'custom_fields'

  def show
    respond_to do |format|
      format.html
    end
  end

  def new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    if @custom_field.save
      redirect_to_index
      return
    end
    render :action => :new
  end

  def edit
    respond_to do |format|
      format.html
    end
  end

  def update
    @custom_field.update_attributes(params[:p_spec_issue_custom_field])
    if @custom_field.save
      redirect_to_index
      return
    end
    render :action => :edit
  end

  def destroy
    @custom_field.destroy
    redirect_to_index    
  end
  
  private
  def find_field
    id = params[:id]
    @custom_field = PSpecIssueCustomField.where(:id => id).first unless id.nil?
    return render_404 if @custom_field.nil?
    @project = @custom_field.project
    return render_404 if @project.nil?
  end
  
  def find_project
    @project = Project.find(params[:id])
  end
  
  def authorize
    return deny_access if !User.current.allowed_to?({:controller => :project_specific_fields, :action => params[:action]}, @project, :global => false)
  end
  
  def build_field_from_params
    @custom_field = PSpecIssueCustomField.new(params[:p_spec_issue_custom_field])
    if params[:p_spec_issue_custom_field]
      @custom_field.share_with_subprojects = params[:p_spec_issue_custom_field][:share_with_subprojects] # force the update to be manual
    end
    @custom_field.project = @project
  end
  
  def redirect_to_index
    redirect_to :controller => :projects, :action => :settings, :id => @project.identifier, :tab => :custom_fields
  end
end

app/helpers/project_specific_field_controller_helper.rb
module ProjectSpecificFieldControllerHelper
end

app/views/project_specific_fields/_custom_field_list.html.erb
<table class="list">
  <thead><tr>
    <th width="30%"><%=l(:field_name)%></th>
    <th><%=l(:field_field_format)%></th>
    <th><%=l(:field_is_required)%></th>
    <th><%=l(:button_sort)%></th>
    <%if User.current().allowed_to?(:delete_project_custom_fields, @project) %>
      <th width="10%"></th>
    <% end %>
  </tr></thead>
  <tbody>
  <% (custom_fields || []).sort.each do |custom_field| -%>
    <tr class="<%= cycle("odd", "even") %>">
      <% if custom_field.project == @project %>
        <td><%= link_to h(custom_field.name), {:controller => :project_specific_fields, :action => 'edit', :id => custom_field} %></td>
        <td align="center"><%= l(custom_field.format.label) %></td>
        <td align="center"><%= checked_image custom_field.is_required? %></td>
        <td align="center" style="width:15%;"><%= reorder_links('p_spec_issue_custom_field', {:controller => :project_specific_fields, :action => 'update', :id => custom_field}, :put) %></td>
        <%if User.current().allowed_to?(:delete_project_custom_fields, @project) %>
          <td class="buttons">
            <%= delete_link :controller => :project_specific_fields, :action => :destroy, :id => custom_field %>
          </td>
        <% end %>
      <%else %>
        <td><%= h(custom_field.name) %></td>
        <td align="center"><%= l(custom_field.format.label) %></td>
        <td align="center"><%= checked_image custom_field.is_required? %></td>
        <td align="center" style="width:15%;"></td>
        <%if User.current().allowed_to?(:delete_project_custom_fields, @project) %>
          <td></td>
        <% end %>
      <% end %>
    </tr>
  <% end; reset_cycle %>
  </tbody>
</table>

<p><%= link_to l(:label_custom_field_new), { :controller => :project_specific_fields, :action => :new, :id => @project.identifier }, :class => 'icon icon-add' %></p>

app/views/project_specific_fields/_form.html.erb
<%= error_messages_for 'custom_field' %>

<div class="splitcontentleft">
<div class="box tabular">
<p><%= f.select :field_format, custom_field_formats_for_select(@custom_field), {}, :disabled => !@custom_field.new_record? %></p>
<p><%= f.text_field :name, :required => true %></p>
<p><%= f.text_area :description, :rows => 7 %></p>

<% if @custom_field.format.multiple_supported %>
<p>
  <%= f.check_box :multiple %>
  <% if !@custom_field.new_record? && @custom_field.multiple %>
  <em class="info"><%= l(:text_turning_multiple_off) %></em>
  <% end %>
</p>
<% end %>

<%= render_custom_field_format_partial f, @custom_field %>

<%= call_hook(:view_custom_fields_form_upper_box, :custom_field => @custom_field, :form => f) %>
</div>
<p><%= submit_tag l(:button_save) %></p>
</div>

<div class="splitcontentright">
<div class="box tabular">
<% case @custom_field.class.name
when "PSpecIssueCustomField" %>
    <p><%= f.check_box :is_required %></p>
    <p><%= f.check_box :is_filter %></p>
    <% if @custom_field.format.searchable_supported %>
    <p><%= f.check_box :searchable %></p>
    <% end %>
    <p>
      <label><%= l(:field_visible) %></label>
      <label class="block">
        <%= radio_button_tag 'custom_field[visible]', 1, @custom_field.visible?, :id => 'custom_field_visible_on',
              :data => {:disables => '.custom_field_role input'} %>
        <%= l(:label_visibility_public) %>
      </label>
      <label class="block">
        <%= radio_button_tag 'p_spec_issue_custom_field[visible]', 0, !@custom_field.visible?, :id => 'custom_field_visible_off',
              :data => {:enables => '.custom_field_role input'} %>
        <%= l(:label_visibility_roles) %>:
      </label>
      <% Role.givable.sorted.each do |role| %>
        <label class="block custom_field_role" style="padding-left:2em;">
          <%= check_box_tag 'p_spec_issue_custom_field[role_ids][]', role.id, @custom_field.roles.include?(role), :id => nil %>
          <%= role.name %>
        </label>
      <% end %>
      <%= hidden_field_tag 'p_spec_issue_custom_field[role_ids][]', '' %>
    </p>

<% else %>
    <p><%= f.check_box :is_required %></p>

<% end %>
<%= call_hook(:"view_custom_fields_form_#{@custom_field.type.to_s.underscore}", :custom_field => @custom_field, :form => f) %>
</div>

<% if @custom_field.is_a?(PSpecIssueCustomField) %>
  <fieldset class="box" id="custom_field_tracker_ids"><legend><%=l(:label_tracker_plural)%></legend>
  <% @project.trackers.sorted.each do |tracker| %>
    <%= check_box_tag "p_spec_issue_custom_field[tracker_ids][]",
                      tracker.id,
                      (@custom_field.trackers.include? tracker),
                      :id => "custom_field_tracker_ids_#{tracker.id}" %>
    <label class="no-css" for="custom_field_tracker_ids_<%=tracker.id%>">
      <%= h(tracker.name) %>
    </label>
  <% end %>
  <%= hidden_field_tag "p_spec_issue_custom_field[tracker_ids][]", '' %>
  <p><%= check_all_links 'custom_field_tracker_ids' %></p>
  </fieldset>
<% end %>
</div>

<% include_calendar_headers_tags %>

app/views/project_specific_fields/_issue_specific_options.html.erb
<div class="box tabular">   
    <fieldset><legend><%=l(:label_tracker_plural)%></legend>
    <% @project.trackers.sorted.all.each do |tracker| %>
      <%= check_box_tag "p_spec_issue_custom_field[tracker_ids][]",
                        tracker.id,
                        (@custom_field.trackers.include? tracker),
                        :id => "custom_field_tracker_ids_#{tracker.id}" %>
      <label class="no-css" for="custom_field_tracker_ids_<%=tracker.id%>">
        <%= h(tracker.name) %>
      </label>
    <% end %>
    <%= hidden_field_tag "p_spec_issue_custom_field[tracker_ids][]", '' %>
    </fieldset>
    &nbsp;
    <p><%= f.check_box :share_with_subprojects %></p>
    <p><%= f.check_box :is_filter %></p>
    <p><%= f.check_box :searchable %></p>
    <% if CustomField.method_defined? :roles %>
      <p>
        <label><%= l(:field_visible) %></label>
        <label class="block">
          <%= radio_button_tag 'p_spec_issue_custom_field[visible]', 1, @custom_field.visible?, :id => 'p_spec_issue_custom_field_visible_on' %>
          <%= l(:label_visibility_public) %>
        </label>
        <label class="block">
          <%= radio_button_tag 'p_spec_issue_custom_field[visible]', 0, !@custom_field.visible?, :id => 'p_spec_issue_custom_field_visible_off' %>
          <%= l(:label_visibility_roles) %>:
        </label>
        <% Role.givable.sorted.each do |role| %>
	  <label class="block custom_field_role" style="padding-left:2em;">
	    <%= check_box_tag 'p_spec_issue_custom_field[role_ids][]', role.id, @custom_field.roles.include?(role) %>
	    <%= role.name %>
	  </label>
        <% end %>
        <%= hidden_field_tag 'p_spec_issue_custom_field[role_ids][]', '' %>
      </p>
    <% end %>
</div>

<% if CustomField.method_defined? :roles %>
  <%= javascript_tag do %>
  function toggleCustomFieldRoles(){
    var checked = $("#p_spec_issue_custom_field_visible_on").is(':checked');
    $('.custom_field_role input').attr('disabled', checked);
  }
  $("#p_spec_issue_custom_field_visible_on, #p_spec_issue_custom_field_visible_off").change(toggleCustomFieldRoles);
  $(document).ready(toggleCustomFieldRoles);
  <% end %>
<% end %>

app/views/project_specific_fields/edit.html.erb
<h2><%= @custom_field.name %></h2>

<%= labelled_form_for [@project, @custom_field], :url => {:controller => :project_specific_fields, :action => :update, :id => @custom_field }, :html => {:id => 'custom_field_form'} do |f| %>
<%= render :partial => 'custom_fields/form', :locals => { :f => f } %>
<%= render :partial => 'issue_specific_options', :locals => { :f => f } %>
<%= hidden_field_tag 'type', @custom_field.type %>
<% end %>

app/views/project_specific_fields/index.html.erb
<table class="list">
  <thead><tr>
    <th width="30%"><%=l(:field_name)%></th>
    <th><%=l(:field_field_format)%></th>
    <th><%=l(:field_is_required)%></th>
    <th><%=l(:button_sort)%></th>
    <%if User.current().allowed_to?(:delete_project_custom_fields, @project) %>
      <th width="10%"></th>
    <% end %>
  </tr></thead>
  <tbody>
  <% (@custom_fields || []).sort.each do |custom_field| -%>
    <tr class="<%= cycle("odd", "even") %>">
      <% if custom_field.project == @project %>
        <td><%= link_to h(custom_field.name), {:controller => :project_specific_fields, :action => 'edit', :id => custom_field} %></td>
        <td align="center"><%= l(Redmine::CustomFieldFormat.label_for(custom_field.field_format)) %></td>
        <td align="center"><%= checked_image custom_field.is_required? %></td>
        <td align="center" style="width:15%;"><%= reorder_links('p_spec_issue_custom_field', {:controller => :project_specific_fields, :action => 'update', :id => custom_field}, :put) %></td>
        <%if User.current().allowed_to?(:delete_project_custom_fields, @project) %>
          <td class="buttons">
            <%= delete_link :controller => :project_specific_fields, :action => :destroy, :id => custom_field %>
          </td>
        <% end %>
      <%else %>
        <td><%= h(custom_field.name) %></td>
        <td align="center"><%= l(Redmine::CustomFieldFormat.label_for(custom_field.field_format)) %></td>
        <td align="center"><%= checked_image custom_field.is_required? %></td>
        <td align="center" style="width:15%;"></td>
        <%if User.current().allowed_to?(:delete_project_custom_fields, @project) %>
          <td></td>
        <% end %>
      <% end %>
    </tr>
  <% end; reset_cycle %>
  </tbody>
</table>

<p><%= link_to l(:label_custom_field_new), { :controller => :project_specific_fields, :action => :new, :id => @project.identifier }, :class => 'icon icon-add' %></p>

app/views/project_specific_fields/new.html.erb
<h2><%= l(:label_custom_field_new) %></h2>

<%= labelled_form_for [@project, @custom_field], :url => {:controller => :project_specific_fields, :action => :create, :id => @project.identifier }, :html => {:id => 'custom_field_form'} do |f| %>
<%= render :partial => 'custom_fields/form', :locals => { :f => f } %>
<%= render :partial => 'issue_specific_options', :locals => { :f => f } %>
<%= hidden_field_tag 'type', @custom_field.type %>
<% end %>

<%= javascript_tag do %>
$('#p_spec_issue_custom_field_field_format').change(function(){
  $.ajax({
    url: '<%= url_for(:action => :new, :format => 'js') %>',
    type: 'get',
    data: $('#custom_field_form').serialize()
  });
});
<% end %>

app/views/project_specific_fields/new.js.erb
$('#content').html('<%= escape_javascript(render :template => 'project_specific_fields/new', :layout => nil, :formats => [:html]) %>')

app/views/project_specific_fields/show.html.erb
<h2>ProjectSpecificFieldControllerController#show</h2>

app/views/projects/settings/_custom_fields.html.erb
<%= render :partial => 'project_specific_fields/custom_field_list', :locals => { :custom_fields => @project.recursive_project_specific_issue_fields } %>